<!--/* Copyright (C) 2020 ShuttleOne - All Rights Reserved */-->
<?

return array(
	"ADMIN_EMAIL" => ADMIN_EMAIL,
	"ROOT_PATH" => ROOT_PATH,
	"CONTEXT" => CONTEXT,
	"TEST" => 0,
	"PLATFORM" => PLATFORM,
	
	"CREATE_DOC" => CREATE_DOC_URL, 
	"CHECK_DOCIC" => CHECK_DOCIC,
	"STATUS_DOC" => STATUS_DOC,
	"LEGAL_OK" => LEGAL_OK,
	"AUDIT_OK" => AUDIT_OK,
	"LEGAL_KYC" => LEGAL_KYC,
	"AUDIT_KYC" => AUDIT_KYC,
	"CHECK_DEBIT" => CHECK_DEBIT,

	"CONTRACT_DETAIL" => CONTRACT_DETAIL,

	"CONTRACT_ACTIVE" => CONTRACT_ACTIVE,


	"CHECK_INTERST" => CHECK_INTERST,




	"LOGIN" => LOGIN,
	"GET_WALLET_WITH_SECTIONID" => GET_WALLET_WITH_SECTIONID,
	"USER_TRANSACTION" => USER_TRANSACTION,

	"RECOVERY_PASSWORD" => RECOVERY_PASSWORD, 
	"USER_DETAIL" => USER_DETAIL,


	"TOPUP_COUNTRY" => TOPUP_COUNTRY,
	"TOPUP_RATE" => TOPUP_RATE,
	"TOPUP_BANK_DETAIL" => TOPUP_BANK_DETAIL,
	"TOPUP_BANK_LIST" => TOPUP_BANK_LIST,
	"TOPUP_CONFIRM" => TOPUP_CONFIRM,

	"TOPUP_BANK_CHECK" => TOPUP_BANK_CHECK,
	"TOPUP_BANK_SUBMIT" => TOPUP_BANK_SUBMIT,
	"TOPUP_DOC_UOLOAD_URL" => TOPUP_DOC_UOLOAD_URL,

	"TOPUP_CHECK_PRICE" => TOPUP_CHECK_PRICE,
	"TOPUP_CONFIRM_RESERVE" => TOPUP_CONFIRM_RESERVE, 
	"TOPUP_CURRENCY" => TOPUP_CURRENCY,


	"WITHDRAW_COUNTRY" => WITHDRAW_COUNTRY,
	"WITHDRAW_RATE" => WITHDRAW_RATE, 
	"WITHDRAW_BKK" => WITHDRAW_BKK,


	"PAYBACK" => PAYBACK,
	
	"NEXT_PERIOD" => NEXT_PERIOD,

	"KYC_CHECK" => KYC_CHECK,

	"ETHER_SCAN" => ETHER_SCAN,
	);

?>